[package]
name = "svelt"
version = "0.1.0"
edition = "2024"

[dependencies]
autocompress = "0.6.0"
blake2 = "0.10.6"
clap = { version = "4.5.39", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
noodles = { version = "0.99.0", features = ["vcf"] }
