[package]
name = "svelt"
version = "0.1.0"
edition = "2024"

[dependencies]
blake2 = "0.10.6"
clap = { version = "4.5.39", features = ["derive"] }
noodles = { version = "0.99.0", features = ["vcf"] }
